version: "3"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "jiraclone"
    expose:
      - 5432
    ports:
      - "5432:5432"
